### ISSUE TITLE
Cannot access the site via "www"

### ISSUE THREAD

**Issue by stu-smith** [cariad/getcodelove.com-bugs#6]
I tend to visit sites by typing the name e.g. `getcodelove` and then hitting`Ctrl+Enter`. This takes me to `www.getcodelove.com` which fails to load with `DNS_PROBE_FINISHED_NXDOMAIN`.

Both http://www.getcodelove.com and https://www.getcodelove.com should redirect to the canonical address.

**Comment by cariad** [comment]
Thanks, Stu! I totally agree, and I’m gonna get this sorted.

**Comment by cariad** [comment]
Holy cow, thanks for raising this! It was a pain in the ass, and I'm glad it's out of the way now. 😁 

I thought I could just put a quick-fix into the existing origin-request lambda function, but the `Host` header at that point is the CloudFront distribution host, and not the original domain name.

I tried whitelisting the `Host` for forwarding in the distribution, but that horribly broke `GET`s from the S3 origin. Turns out you can't forward *that* header for S3 origins.

In the end, I put the redirect code in a new viewer-request lambda. I've got the "real" hostname at that point, because it's pre-distribution. The only downside I can think of is that the 301 response won't get cached, but I can't imagine that my lambda quota is under threat. 😛 

So, this is fixed in https://github.com/cariad/aws-jekyll-pipeline/pull/1 and has been deployed.

These links should end up redirecting to the correct, canonical location:

- http://www.getcodelove.com now redirects to https://getcodelove.com
- https://www.getcodelove.com now also redirects to https://getcodelove.com/
